### PR TITLE
Traditional Chinese translation

### PR DESCRIPTION
**Pull request by ladios**

### CODE REVIEW

**Comment by ladios** [comment]
I wonder whether you will be notified if commits updated in old pull requests.

**Comment by ladios** [comment]
@koush: Traditional Chinese translation updated for (bfdb50b new resources by @vazguard!)

**Comment by ladios** [comment]
@koush: Traditional Chinese translation updated for b6da1bb & dc02f70.
A suggestion: Remove outdated whatsnew translation if we translators couldn't update that in time.

**Comment by koush** [comment]
Yeah, I think I may remove the whatsnew from localization altogether.

**Comment by ladios** [comment]
@koush: Traditional Chinese translation updated for (61a6bbd show a "loading comments" screen.)

**Comment by ladios** [comment]
@koush: Traditional Chinese translation updated for 8b5ed13, 906135f

**Pull request closed without merging**
