### PR TITLE
New Traditional Chinese translation

### PR DESCRIPTION
**Pull request by ladios**
Please merge... for heaven's sake! I make it right this time.
Your new so-called Chinese translation, which is actually Simplified Chinese, hit every Traditional Chinese user in the eyes!

### CODE REVIEW

**Comment by koush** [comment]
Haha, I'm sorry. I do not read chinese, so it is hard for me to know what is correct and what is not. However, the translation I did was for simplified chinese. Would this not belong in the following:

values-zh-rCN
values-zh-rTW

Let me know.

**Comment by ladios** [comment]
values-zh-rCN = Simplified Chinese
values-zh-rTW = Traditional Chinese

**Comment by koush** [comment]
I think you edited the wrong file? I did not have everything checked in. You changed the taiwanese translation, you need to modify values-zh.

**Comment by koush** [comment]
Ok everything is checked in now. Let me post an updated apk for you to test.

**Comment by ladios** [comment]
I can't follow up all those renamings. Given up and re-commited a new one.

**Pull request closed without merging**
